<?php
/**
 * CreateAssociateRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CrowdProperty\ModulrHmacPhpClient
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Modulr API
 *
 * Modulo API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CrowdProperty\ModulrHmacPhpClient\Model;

use \ArrayAccess;

/**
 * CreateAssociateRequest Class Doc Comment
 *
 * @category    Class
 * @package     CrowdProperty\ModulrHmacPhpClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateAssociateRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CreateAssociateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'applicant' => 'bool',
        'date_of_birth' => 'string',
        'document_info' => '\CrowdProperty\ModulrHmacPhpClient\Model\Document[]',
        'email' => 'string',
        'first_name' => 'string',
        'home_address' => '\CrowdProperty\ModulrHmacPhpClient\Model\AddressRequest',
        'last_name' => 'string',
        'middle_name' => 'string',
        'ownership' => 'int',
        'phone' => 'string',
        'type' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'applicant' => 'applicant',
        'date_of_birth' => 'dateOfBirth',
        'document_info' => 'documentInfo',
        'email' => 'email',
        'first_name' => 'firstName',
        'home_address' => 'homeAddress',
        'last_name' => 'lastName',
        'middle_name' => 'middleName',
        'ownership' => 'ownership',
        'phone' => 'phone',
        'type' => 'type'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'applicant' => 'setApplicant',
        'date_of_birth' => 'setDateOfBirth',
        'document_info' => 'setDocumentInfo',
        'email' => 'setEmail',
        'first_name' => 'setFirstName',
        'home_address' => 'setHomeAddress',
        'last_name' => 'setLastName',
        'middle_name' => 'setMiddleName',
        'ownership' => 'setOwnership',
        'phone' => 'setPhone',
        'type' => 'setType'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'applicant' => 'getApplicant',
        'date_of_birth' => 'getDateOfBirth',
        'document_info' => 'getDocumentInfo',
        'email' => 'getEmail',
        'first_name' => 'getFirstName',
        'home_address' => 'getHomeAddress',
        'last_name' => 'getLastName',
        'middle_name' => 'getMiddleName',
        'ownership' => 'getOwnership',
        'phone' => 'getPhone',
        'type' => 'getType'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const TYPE_DIRECTOR = 'DIRECTOR';
    const TYPE_PARTNER = 'PARTNER';
    const TYPE_CSECRETARY = 'CSECRETARY';
    const TYPE_SOLETRADER = 'SOLETRADER';
    const TYPE_BENE_OWNER = 'BENE_OWNER';
    const TYPE_C_INTEREST = 'C_INTEREST';
    const TYPE_INDIVIDUAL = 'INDIVIDUAL';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_DIRECTOR,
            self::TYPE_PARTNER,
            self::TYPE_CSECRETARY,
            self::TYPE_SOLETRADER,
            self::TYPE_BENE_OWNER,
            self::TYPE_C_INTEREST,
            self::TYPE_INDIVIDUAL,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['applicant'] = isset($data['applicant']) ? $data['applicant'] : null;
        $this->container['date_of_birth'] = isset($data['date_of_birth']) ? $data['date_of_birth'] : null;
        $this->container['document_info'] = isset($data['document_info']) ? $data['document_info'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['home_address'] = isset($data['home_address']) ? $data['home_address'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['middle_name'] = isset($data['middle_name']) ? $data['middle_name'] : null;
        $this->container['ownership'] = isset($data['ownership']) ? $data['ownership'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['date_of_birth'] === null) {
            $invalid_properties[] = "'date_of_birth' can't be null";
        }
        if (!is_null($this->container['email']) && (strlen($this->container['email']) > 100)) {
            $invalid_properties[] = "invalid value for 'email', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['email']) && !preg_match("/[^\\s@]+@[^\\s@]+\\.[^\\s@]+/", $this->container['email'])) {
            $invalid_properties[] = "invalid value for 'email', must be conform to the pattern /[^\\s@]+@[^\\s@]+\\.[^\\s@]+/.";
        }

        if ($this->container['first_name'] === null) {
            $invalid_properties[] = "'first_name' can't be null";
        }
        if ((strlen($this->container['first_name']) > 100)) {
            $invalid_properties[] = "invalid value for 'first_name', the character length must be smaller than or equal to 100.";
        }

        if ((strlen($this->container['first_name']) < 1)) {
            $invalid_properties[] = "invalid value for 'first_name', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[\\p{L}' -]+$/", $this->container['first_name'])) {
            $invalid_properties[] = "invalid value for 'first_name', must be conform to the pattern /^[\\p{L}' -]+$/.";
        }

        if ($this->container['home_address'] === null) {
            $invalid_properties[] = "'home_address' can't be null";
        }
        if ($this->container['last_name'] === null) {
            $invalid_properties[] = "'last_name' can't be null";
        }
        if ((strlen($this->container['last_name']) > 100)) {
            $invalid_properties[] = "invalid value for 'last_name', the character length must be smaller than or equal to 100.";
        }

        if ((strlen($this->container['last_name']) < 1)) {
            $invalid_properties[] = "invalid value for 'last_name', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[\\p{L}' -]+$/", $this->container['last_name'])) {
            $invalid_properties[] = "invalid value for 'last_name', must be conform to the pattern /^[\\p{L}' -]+$/.";
        }

        if (!is_null($this->container['middle_name']) && !preg_match("/^[\\p{L}' -]*$/", $this->container['middle_name'])) {
            $invalid_properties[] = "invalid value for 'middle_name', must be conform to the pattern /^[\\p{L}' -]*$/.";
        }

        if (!is_null($this->container['ownership']) && ($this->container['ownership'] > 100)) {
            $invalid_properties[] = "invalid value for 'ownership', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['ownership']) && ($this->container['ownership'] < 1)) {
            $invalid_properties[] = "invalid value for 'ownership', must be bigger than or equal to 1.";
        }

        if ($this->container['type'] === null) {
            $invalid_properties[] = "'type' can't be null";
        }
        $allowed_values = ["DIRECTOR", "PARTNER", "CSECRETARY", "SOLETRADER", "BENE_OWNER", "C_INTEREST", "INDIVIDUAL"];
        if (!in_array($this->container['type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'type', must be one of 'DIRECTOR', 'PARTNER', 'CSECRETARY', 'SOLETRADER', 'BENE_OWNER', 'C_INTEREST', 'INDIVIDUAL'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['date_of_birth'] === null) {
            return false;
        }
        if (strlen($this->container['email']) > 100) {
            return false;
        }
        if (!preg_match("/[^\\s@]+@[^\\s@]+\\.[^\\s@]+/", $this->container['email'])) {
            return false;
        }
        if ($this->container['first_name'] === null) {
            return false;
        }
        if (strlen($this->container['first_name']) > 100) {
            return false;
        }
        if (strlen($this->container['first_name']) < 1) {
            return false;
        }
        if (!preg_match("/^[\\p{L}' -]+$/", $this->container['first_name'])) {
            return false;
        }
        if ($this->container['home_address'] === null) {
            return false;
        }
        if ($this->container['last_name'] === null) {
            return false;
        }
        if (strlen($this->container['last_name']) > 100) {
            return false;
        }
        if (strlen($this->container['last_name']) < 1) {
            return false;
        }
        if (!preg_match("/^[\\p{L}' -]+$/", $this->container['last_name'])) {
            return false;
        }
        if (!preg_match("/^[\\p{L}' -]*$/", $this->container['middle_name'])) {
            return false;
        }
        if ($this->container['ownership'] > 100) {
            return false;
        }
        if ($this->container['ownership'] < 1) {
            return false;
        }
        if ($this->container['type'] === null) {
            return false;
        }
        $allowed_values = ["DIRECTOR", "PARTNER", "CSECRETARY", "SOLETRADER", "BENE_OWNER", "C_INTEREST", "INDIVIDUAL"];
        if (!in_array($this->container['type'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets applicant
     * @return bool
     */
    public function getApplicant()
    {
        return $this->container['applicant'];
    }

    /**
     * Sets applicant
     * @param bool $applicant Indciates if the associate is the applicant. Only one associate should be marked as such
     * @return $this
     */
    public function setApplicant($applicant)
    {
        $this->container['applicant'] = $applicant;

        return $this;
    }

    /**
     * Gets date_of_birth
     * @return string
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     * @param string $date_of_birth Date in yyyy-MM-dd format. Valid age is from 18 to 100 years
     * @return $this
     */
    public function setDateOfBirth($date_of_birth)
    {
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets document_info
     * @return \CrowdProperty\ModulrHmacPhpClient\Model\Document[]
     */
    public function getDocumentInfo()
    {
        return $this->container['document_info'];
    }

    /**
     * Sets document_info
     * @param \CrowdProperty\ModulrHmacPhpClient\Model\Document[] $document_info information on uploaded documents
     * @return $this
     */
    public function setDocumentInfo($document_info)
    {
        $this->container['document_info'] = $document_info;

        return $this;
    }

    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     * @param string $email Contact email address for applicants
     * @return $this
     */
    public function setEmail($email)
    {
        if (!is_null($email) && (strlen($email) > 100)) {
            throw new \InvalidArgumentException('invalid length for $email when calling CreateAssociateRequest., must be smaller than or equal to 100.');
        }
        if (!is_null($email) && (!preg_match("/[^\\s@]+@[^\\s@]+\\.[^\\s@]+/", $email))) {
            throw new \InvalidArgumentException("invalid value for $email when calling CreateAssociateRequest., must conform to the pattern /[^\\s@]+@[^\\s@]+\\.[^\\s@]+/.");
        }

        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets first_name
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     * @param string $first_name Letters, hyphens and apostrophes
     * @return $this
     */
    public function setFirstName($first_name)
    {
        if ((strlen($first_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $first_name when calling CreateAssociateRequest., must be smaller than or equal to 100.');
        }
        if ((strlen($first_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $first_name when calling CreateAssociateRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[\\p{L}' -]+$/", $first_name))) {
            throw new \InvalidArgumentException("invalid value for $first_name when calling CreateAssociateRequest., must conform to the pattern /^[\\p{L}' -]+$/.");
        }

        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets home_address
     * @return \CrowdProperty\ModulrHmacPhpClient\Model\AddressRequest
     */
    public function getHomeAddress()
    {
        return $this->container['home_address'];
    }

    /**
     * Sets home_address
     * @param \CrowdProperty\ModulrHmacPhpClient\Model\AddressRequest $home_address Home address
     * @return $this
     */
    public function setHomeAddress($home_address)
    {
        $this->container['home_address'] = $home_address;

        return $this;
    }

    /**
     * Gets last_name
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     * @param string $last_name Letters, hyphens and apostrophes
     * @return $this
     */
    public function setLastName($last_name)
    {
        if ((strlen($last_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $last_name when calling CreateAssociateRequest., must be smaller than or equal to 100.');
        }
        if ((strlen($last_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $last_name when calling CreateAssociateRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[\\p{L}' -]+$/", $last_name))) {
            throw new \InvalidArgumentException("invalid value for $last_name when calling CreateAssociateRequest., must conform to the pattern /^[\\p{L}' -]+$/.");
        }

        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets middle_name
     * @return string
     */
    public function getMiddleName()
    {
        return $this->container['middle_name'];
    }

    /**
     * Sets middle_name
     * @param string $middle_name Letters, hyphens and apostrophes
     * @return $this
     */
    public function setMiddleName($middle_name)
    {

        if (!is_null($middle_name) && (!preg_match("/^[\\p{L}' -]*$/", $middle_name))) {
            throw new \InvalidArgumentException("invalid value for $middle_name when calling CreateAssociateRequest., must conform to the pattern /^[\\p{L}' -]*$/.");
        }

        $this->container['middle_name'] = $middle_name;

        return $this;
    }

    /**
     * Gets ownership
     * @return int
     */
    public function getOwnership()
    {
        return $this->container['ownership'];
    }

    /**
     * Sets ownership
     * @param int $ownership Ownwership percentage for Partners
     * @return $this
     */
    public function setOwnership($ownership)
    {

        if (!is_null($ownership) && ($ownership > 100)) {
            throw new \InvalidArgumentException('invalid value for $ownership when calling CreateAssociateRequest., must be smaller than or equal to 100.');
        }
        if (!is_null($ownership) && ($ownership < 1)) {
            throw new \InvalidArgumentException('invalid value for $ownership when calling CreateAssociateRequest., must be bigger than or equal to 1.');
        }

        $this->container['ownership'] = $ownership;

        return $this;
    }

    /**
     * Gets phone
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     * @param string $phone Contact phone number for applicants
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type Type of associate
     * @return $this
     */
    public function setType($type)
    {
        $allowed_values = array('DIRECTOR', 'PARTNER', 'CSECRETARY', 'SOLETRADER', 'BENE_OWNER', 'C_INTEREST', 'INDIVIDUAL');
        if ((!in_array($type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'type', must be one of 'DIRECTOR', 'PARTNER', 'CSECRETARY', 'SOLETRADER', 'BENE_OWNER', 'C_INTEREST', 'INDIVIDUAL'");
        }
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CrowdProperty\ModulrHmacPhpClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CrowdProperty\ModulrHmacPhpClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


