<?php
/**
 * CreateBeneficiaryRequest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   Swaagger Codegen team
 *
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Modulr API.
 *
 * Modulo API
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CrowdProperty\ModulrHmacPhpClient\Model;

use ArrayAccess;

/**
 * CreateBeneficiaryRequest Class Doc Comment.
 *
 * @category    Class
 *
 * @author      Swagger Codegen team
 *
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateBeneficiaryRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'CreateBeneficiaryRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'default_reference'      => 'string',
        'destination_identifier' => '\CrowdProperty\ModulrHmacPhpClient\Model\IdentifierRequest',
        'external_reference'     => 'string',
        'name'                   => 'string',
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default_reference'      => 'defaultReference',
        'destination_identifier' => 'destinationIdentifier',
        'external_reference'     => 'externalReference',
        'name'                   => 'name',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'default_reference'      => 'setDefaultReference',
        'destination_identifier' => 'setDestinationIdentifier',
        'external_reference'     => 'setExternalReference',
        'name'                   => 'setName',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'default_reference'      => 'getDefaultReference',
        'destination_identifier' => 'getDestinationIdentifier',
        'external_reference'     => 'getExternalReference',
        'name'                   => 'getName',
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['default_reference'] = isset($data['default_reference']) ? $data['default_reference'] : null;
        $this->container['destination_identifier'] = isset($data['destination_identifier']) ? $data['destination_identifier'] : null;
        $this->container['external_reference'] = isset($data['external_reference']) ? $data['external_reference'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['default_reference'] === null) {
            $invalid_properties[] = "'default_reference' can't be null";
        }
        if ($this->container['destination_identifier'] === null) {
            $invalid_properties[] = "'destination_identifier' can't be null";
        }
        if (!is_null($this->container['external_reference']) && (strlen($this->container['external_reference']) > 50)) {
            $invalid_properties[] = "invalid value for 'external_reference', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['external_reference']) && !preg_match('/[\\w-\\s]*_/', $this->container['external_reference'])) {
            $invalid_properties[] = "invalid value for 'external_reference', must be conform to the pattern /[\\w-\\s]*_/.";
        }

        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ((strlen($this->container['name']) > 100)) {
            $invalid_properties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if (!preg_match("/^(.*?[A-Za-z0-9]){1,}['\\.\\-/&\\s]*_/", $this->container['name'])) {
            $invalid_properties[] = "invalid value for 'name', must be conform to the pattern /^(.*?[A-Za-z0-9]){1,}['\\.\\-/&\\s]*_/.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        if ($this->container['default_reference'] === null) {
            return false;
        }
        if ($this->container['destination_identifier'] === null) {
            return false;
        }
        if (strlen($this->container['external_reference']) > 50) {
            return false;
        }
        if (!preg_match('/[\\w-\\s]*_/', $this->container['external_reference'])) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if (strlen($this->container['name']) > 100) {
            return false;
        }
        if (!preg_match("/^(.*?[A-Za-z0-9]){1,}['\\.\\-/&\\s]*_/", $this->container['name'])) {
            return false;
        }

        return true;
    }

    /**
     * Gets default_reference.
     *
     * @return string
     */
    public function getDefaultReference()
    {
        return $this->container['default_reference'];
    }

    /**
     * Sets default_reference.
     *
     * @param string $default_reference
     *
     * @return $this
     */
    public function setDefaultReference($default_reference)
    {
        $this->container['default_reference'] = $default_reference;

        return $this;
    }

    /**
     * Gets destination_identifier.
     *
     * @return \CrowdProperty\ModulrHmacPhpClient\Model\IdentifierRequest
     */
    public function getDestinationIdentifier()
    {
        return $this->container['destination_identifier'];
    }

    /**
     * Sets destination_identifier.
     *
     * @param \CrowdProperty\ModulrHmacPhpClient\Model\IdentifierRequest $destination_identifier
     *
     * @return $this
     */
    public function setDestinationIdentifier($destination_identifier)
    {
        $this->container['destination_identifier'] = $destination_identifier;

        return $this;
    }

    /**
     * Gets external_reference.
     *
     * @return string
     */
    public function getExternalReference()
    {
        return $this->container['external_reference'];
    }

    /**
     * Sets external_reference.
     *
     * @param string $external_reference
     *
     * @return $this
     */
    public function setExternalReference($external_reference)
    {
        if (!is_null($external_reference) && (strlen($external_reference) > 50)) {
            throw new \InvalidArgumentException('invalid length for $external_reference when calling CreateBeneficiaryRequest., must be smaller than or equal to 50.');
        }
        if (!is_null($external_reference) && (!preg_match('/[\\w-\\s]*_/', $external_reference))) {
            throw new \InvalidArgumentException("invalid value for $external_reference when calling CreateBeneficiaryRequest., must conform to the pattern /[\\w-\\s]*_/.");
        }

        $this->container['external_reference'] = $external_reference;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name.
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((strlen($name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateBeneficiaryRequest., must be smaller than or equal to 100.');
        }
        if ((!preg_match("/^(.*?[A-Za-z0-9]){1,}['\\.\\-/&\\s]*_/", $name))) {
            throw new \InvalidArgumentException("invalid value for $name when calling CreateBeneficiaryRequest., must conform to the pattern /^(.*?[A-Za-z0-9]){1,}['\\.\\-/&\\s]*_/.");
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CrowdProperty\ModulrHmacPhpClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CrowdProperty\ModulrHmacPhpClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}
