<?php
/**
 * InboundpaymentsApi
 * PHP version 5
 *
 * @category Class
 * @package  CrowdProperty\ModulrHmacPhpClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Modulr API
 *
 * Modulo API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CrowdProperty\ModulrHmacPhpClient\Api;

use \CrowdProperty\ModulrHmacPhpClient\ApiClient;
use \CrowdProperty\ModulrHmacPhpClient\ApiException;
use \CrowdProperty\ModulrHmacPhpClient\Configuration;
use \CrowdProperty\ModulrHmacPhpClient\ObjectSerializer;

/**
 * InboundpaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  CrowdProperty\ModulrHmacPhpClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundpaymentsApi
{
    /**
     * API Client
     *
     * @var \CrowdProperty\ModulrHmacPhpClient\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \CrowdProperty\ModulrHmacPhpClient\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\CrowdProperty\ModulrHmacPhpClient\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \CrowdProperty\ModulrHmacPhpClient\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \CrowdProperty\ModulrHmacPhpClient\ApiClient $apiClient set the API client
     *
     * @return InboundpaymentsApi
     */
    public function setApiClient(\CrowdProperty\ModulrHmacPhpClient\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createPaymentUsingPOST
     *
     * Generate a mock incoming payment
     *
     * @param \CrowdProperty\ModulrHmacPhpClient\Model\InboundPaymentRequest $credit_request Details of credit to the account (optional)
     * @throws \CrowdProperty\ModulrHmacPhpClient\ApiException on non-2xx response
     * @return void
     */
    public function createPaymentUsingPOST($credit_request = null)
    {
        list($response) = $this->createPaymentUsingPOSTWithHttpInfo($credit_request);
        return $response;
    }

    /**
     * Operation createPaymentUsingPOSTWithHttpInfo
     *
     * Generate a mock incoming payment
     *
     * @param \CrowdProperty\ModulrHmacPhpClient\Model\InboundPaymentRequest $credit_request Details of credit to the account (optional)
     * @throws \CrowdProperty\ModulrHmacPhpClient\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPaymentUsingPOSTWithHttpInfo($credit_request = null)
    {
        // parse inputs
        $resourcePath = "/credit";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=UTF-8']);

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($credit_request)) {
            $_tempBody = $credit_request;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey) !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/credit'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }
}
